services:
  postgres:
    image: postgres:17
    container_name: nest-graphql-database
    restart: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: eyadroshnikov/nest-graphql-backend:1
    container_name: nest-graphql-backend
    restart: on-failure
    ports:
      - '3000:3000'
    env_file:
      - '.env'
    depends_on:
      - postgres
volumes:
  postgres_data:
